### ISSUE TITLE
arewefastyet.rs does not appear to be actively maintained

### ISSUE THREAD

**Issue by nonl4331** [UgurcanAkkok/AreWeRustYet#13]
The website https://arewefastyet.rs contained in the list does not appear to be actively maintained and has an expired SSL certificate. The website also appears to redirect to an unrelated website.

**Comment by nonl4331** [comment]
See [pull request #14](https://github.com/UgurcanAkkok/AreWeRustYet/pull/14)

**Comment by UgurcanAkkok** [comment]
Merged #14, thanks!
