### ISSUE TITLE
Remove AreWeAudioYet

### ISSUE THREAD

**Issue by VolkerSchlegel** [UgurcanAkkok/AreWeRustYet#21]
See https://github.com/RustAudio/areweaudioyet/issues/15
As mentioned there https://rust.audio/ seems to be the current alternative.

**Comment by UgurcanAkkok** [comment]
Thanks, I am looking into it.

**Comment by UgurcanAkkok** [comment]
fixed by ae6e69147a6829ee62162f483558c3fadc665240
