### ISSUE TITLE
wiki.mozilla.org/areweyet

### ISSUE THREAD

**Issue by ibraheemdev** [UgurcanAkkok/AreWeRustYet#3]
Just a heads up, this already exists here:
https://wiki.mozilla.org/areweyet

It looks like it is a complete listing of all the areweblankyet sites

**Comment by simonsan** [comment]
> 
> 
> Just a heads up, this already exists here:
> https://wiki.mozilla.org/areweyet
> 
> It looks like it is a complete listing of all the areweblankyet sites

It's also nice to have, I like this list here more honestly, because it's clearer. Why not linking this wiki in here as `Other related areweXyet-lists` or so?

**Comment by UgurcanAkkok** [comment]
I referenced it in a commit because I used it but we can also put it in README

**Comment by UgurcanAkkok** [comment]
Thanks for the issue, I added it.
