### ISSUE TITLE
add arewefastyet

### ISSUE THREAD

**Issue by ibraheemdev** [UgurcanAkkok/AreWeRustYet#7]
UPDATED: [arewefastyet](https://arewefastyet.rs/)

**Comment by UgurcanAkkok** [comment]
I could not find any about page or description, what is it exactly showing? What is the purpose of the site overall?

**Comment by ibraheemdev** [comment]
Oh sorry, I realized I linked to arewefastyet.com instead of arewefastyet.rs. It is visualizing the speed increase of the rust compiler over the years

**Comment by UgurcanAkkok** [comment]
Thanks for the suggestion!
